### ISSUE TITLE
Constructor injection gives the following error

### ISSUE THREAD

**Issue by codebanesr** [rejvban/nestjs-twilio#3]
'TwilioClient' refers to a value, but is being used as a type here. Did you mean 'typeof TwilioClient'?ts(2749)
Parameter 'client' of constructor from exported class has or is using private name 'TwilioClient'.ts(4063)

Ubuntu 20.10
Nestjs

```ts
  constructor(
    @InjectTwilio() 
    private readonly client: TwilioClient
  ) {}

**Comment by lkaric** [comment]
@shanurrahman Sorry for the inconvenience, the issue is resolved.

**Comment by codebanesr** [comment]
Thanks

**Comment by abdallahbedir2** [comment]
Why `InjectTwilio` is no longer exported?

**Comment by lkaric** [comment]
@abdallahbedir2 Because of the architectural changes and introduction of the configurable module builder. It should still be available with older versions, but I do not provide any support for legacy syntax.

Any specific use case that cannot be done with the standard (current) approach? If so, please open a new issue with the minimal reproduction.
