### ISSUE TITLE
Configurable module import dependency resolution error

### ISSUE THREAD

**Issue by harshmodi3812** [rejvban/nestjs-twilio#60]
# Bug Report

## Describe the Bug

[Nest] 21260  - 20/07/2023, 9:57:29 pm   ERROR [ExceptionHandler] Nest can't resolve dependencies of the TwilioService (?). Please make sure that the argument CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] at index [0] is available in the TwilioModule context.

Potential solutions:
- Is TwilioModule a valid NestJS module?
- If CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] is a provider, is it part of the current TwilioModule?
- If CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] is exported from a separate @Module, is that module imported within TwilioModule?
  @Module({
    imports: [ /* the Module containing CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] */ ]
  })

Error: Nest can't resolve dependencies of the TwilioService (?). Please make sure that the argument CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] at index [0] is available in the TwilioModule context.

Potential solutions:
- Is TwilioModule a valid NestJS module?
- If CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] is a provider, is it part of the current TwilioModule?
- If CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] is exported from a separate @Module, is that module imported within TwilioModule?
  @Module({
    imports: [ /* the Module containing CONFIGURABLE_MODULE_OPTIONS[fabf635f2b63dc62a1ece] */ ]
  })

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add TwilioModule.forRootAsync... as defined in app.module.ts
2. Add TwilioService to the constructor of a service
3. Import TwilioModule in the *.module.ts for that service

## Expected Behavior

No dependency injection error

## Error

Error resulted by the potential bug.

## Your Environment

- OS: Windows
- Version of nestjs-twilio: v3.2.0

## Error reproducing steps

Please explain how did your error ocurr, you can also leave gists, repos or any kind of codebase.

## Additional Information

Any other information about the problem here.

**Comment by lkaric** [comment]
What version of Nestjs are you using?

**Comment by harshmodi3812** [comment]
Nestjs version 10.1.7

**Comment by lkaric** [comment]
Can you provide an implementation (just redact secrets and/or any sensitive business logi), I can't get the issue to reproduce

**Comment by alex-reusables** [comment]
I am seeing this issue at the moment with NestJS 11 and the latest version of this package (4.4.0).
I notice there are a number of nearly identical issues in this repo, but all are stale. This is my init code:

```
    ConfigModule.forRoot({
      isGlobal: true, <- set to global
      load: [configuration],
    }),
    TwilioModule.forRootAsync({
      imports: [ConfigModule], <- have tried with and without this
      isGlobal: true,  <- added this recently but to no avail
      useFactory: (configService: ConfigService) => ({
        accountSid: configService.get('twilio.account_sid'),
        authToken: configService.get('twilio.auth_token'),
      }),
      inject: [ConfigService],
    })
```

I was previously initializing TwilioModule in all modules that needed it, but this lead to duplicate sms being sent.

**Update: Resolved** 

By declaring the module global in app.module, I am able to use TwilioService directly in other services, so no need to import TwilioModule in other modules. I believe the failure to config was due to those other imports of TwilioModule.
Without `isGlobal` in TwilioModule setup in app.module, not sure what one would do, I suppose that would imply multiple instances of TwilioModule were acceptable.
